/* Offline Tengwar generator for Arda.
 *
 * Drives the Glǽmscribe engine (AGPL, used here strictly as a build-time tool —
 * its code is NOT shipped with the site) to transcribe every Sindarin line and
 * title from data/songs.js into the "Sindarin — Tengwar (general use)" mode,
 * output in the glaem-unicode Annatar charset, and writes data/tengwar.js:
 *
 *     window.ARDA_TENGWAR = { "<source text>": "<tengwar codepoints>", ... }
 *
 * The page merges this map at runtime; the paired font
 * assets/fonts/tengwar-annatar-glaemunicode.ttf renders the codepoints.
 *
 * Regenerate after editing lyrics:   node scripts/transcribe-tengwar.mjs
 * Engine resources are expected under .tooling/glaemscribe/js (gitignored),
 * overridable with GLAEMSCRIBE_JS=/path/to/glaemscribe/js
 */
import fs from "fs";
import vm from "vm";
import path from "path";
import { fileURLToPath } from "url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const JS = process.env.GLAEMSCRIBE_JS || path.join(ROOT, ".tooling/glaemscribe/js");
const MODE = "sindarin-tengwar-general_use";
const CHARSET = "tengwar_guni_annatar";

if (!fs.existsSync(path.join(JS, "glaemscribe.js"))) {
  console.error(`Glǽmscribe engine not found at ${JS}\n` +
    `Set GLAEMSCRIBE_JS, or vendor it: clone github.com/BenTalagan/glaemscribe,\n` +
    `extract build/npm/glaemscribe-*.tgz, copy package/js -> .tooling/glaemscribe/js`);
  process.exit(1);
}

function loadSongs() {
  const sandbox = { window: {} };
  vm.runInNewContext(fs.readFileSync(path.join(ROOT, "data/songs.js"), "utf8"), sandbox);
  return sandbox.window.ARDA_SONGS;
}

function makeTranscriber() {
  const G = {}; G.window = G; G.global = G; G.navigator = {}; G.console = console;
  vm.createContext(G);
  const run = (f) => vm.runInContext(fs.readFileSync(f, "utf8"), G, { filename: f });
  run(path.join(JS, "glaemscribe.js"));
  for (const f of fs.readdirSync(path.join(JS, "charsets"))) run(path.join(JS, "charsets", f));
  run(path.join(JS, "modes", `${MODE}.glaem.js`));
  const rm = G.Glaemscribe.resource_manager;
  rm.load_charsets([CHARSET]);
  rm.load_modes([MODE]);
  const mode = rm.loaded_modes[MODE];
  const charset = rm.loaded_charsets[CHARSET];
  if (!mode || !charset) throw new Error("failed to load mode or charset");
  return (text) => {
    const r = mode.transcribe(text, charset);
    if (!r[0]) throw new Error(`transcription failed for "${text}": ${r[1]}`);
    return r[1];
  };
}

const songs = loadSongs();
const transcribe = makeTranscriber();

const map = {};
let count = 0;
const add = (text) => {
  if (text && !(text in map)) { map[text] = transcribe(text); count++; }
};
const UI_STRINGS = ["Arda"]; // standalone words used as page chrome (wordmark, hero)
for (const s of UI_STRINGS) add(s);
for (const song of songs) {
  add(song.title);
  for (const section of song.sections) for (const line of section.lines) add(line.sin);
}

const out = "/* Generated by scripts/transcribe-tengwar.mjs — do not edit by hand. */\n" +
  "(function (root) {\n  root.ARDA_TENGWAR = " +
  JSON.stringify(map, null, 2).replace(/\n/g, "\n  ") +
  ";\n})(typeof window !== \"undefined\" ? window : globalThis);\n";
fs.writeFileSync(path.join(ROOT, "data/tengwar.js"), out);
console.log(`Wrote data/tengwar.js — ${count} unique strings transcribed (${MODE} / ${CHARSET}).`);
